# File: logger.dist.yml
# This is an template config file for the eventum setup.
# Setup will process this and save as config/logger.yml.
# You can remove this comment :)
#
# Logger configuration for Eventum
#

formatters:
    default:
        class: Monolog\Formatter\LineFormatter
        format: "[%datetime%] %channel%.%level_name%: %message% %context% %extra%\n"
    error_handler:
        class: Monolog\Formatter\LineFormatter
        format: "%channel%.%level_name%: %message% %context% %extra%"

handlers:
    app_log:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: default
        stream: ../var/log/eventum.log
        filePermission: 0640
    auth_log:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: default
        stream: ../var/log/auth.log
        filePermission: 0640
    cli_log:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: default
        stream: ../var/log/cli.log
        filePermission: 0640
#    error_mailer:
#        class: Eventum\Monolog\MailHandler
#        level: ERROR
    error_handler:
        class: Monolog\Handler\ErrorLogHandler
        formatter: error_handler

processors:
    web_processor:
        class: Monolog\Processor\WebProcessor
    memory_processor:
        class: Monolog\Processor\MemoryUsageProcessor
    memory_peak_processor:
        class: Monolog\Processor\MemoryPeakUsageProcessor
    eventum_app_info_processor:
        class: Eventum\Monolog\AppInfoProcessor

loggers:
    # app logger is the default, the other loggers are optional and inherit from app logger if not defined
    app:
        handlers: [app_log, error_handler]
        processors: [web_processor, memory_processor, memory_peak_processor, eventum_app_info_processor]
    auth:
        handlers: [auth_log, error_handler]
        processors: [web_processor, memory_processor, memory_peak_processor, eventum_app_info_processor]
    cli:
        handlers: [cli_log, error_handler]
        processors: [web_processor, memory_processor, memory_peak_processor, eventum_app_info_processor]
